name: Google 검색 색인 삭제 요청

on:
  repository_dispatch:
    types:
      - indexnow-delete

concurrency:
  group: google-workflow-group
  cancel-in-progress: false

jobs:
  indexing_request:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: 저장소 업데이트
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 의존성 설치
        run: pip install google-auth requests

      - name: 인증 정보 설정
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "${GOOGLE_APPLICATION_CREDENTIALS}" > .github/workflows/credentials.json

      - name: 삭제된 파일 목록 환경 변수 설정
        run: |
          DELETED_FILES="${{ join(github.event.client_payload.deleted_files, ',') }}"
          echo "JSON_FILES=$DELETED_FILES" >> $GITHUB_ENV
          echo "삭제된 파일 목록: $DELETED_FILES"

      - name: Python 스크립트 실행
        run: python .github/workflows/gsc_delete-indexing.py
      - name: 변경 사항 커밋 및 푸시
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gsc-index-status.md
          git commit -m "Update GSC index status log"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pages 배포 워크플로우 호출
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/${{ github.repository }}/dispatches \
               -d "{\"event_type\": \"pages-deploy\"}"
